11-Django-Class-Based-Views/school_site/classroom/urls.py
from django.urls import path


from .views import (HomeView,ThankYouView, 
                    ContactFormView, TeacherCreateView,
                    TeacherListView,TeacherUpdateView,
                    TeacherDeleteView,TeacherDetailView)

app_name = 'classroom'

urlpatterns = [ 
    path('',HomeView.as_view(),name='home'), 
    path('contact/',ContactFormView.as_view(),name='contact'),
    path('thank_you/',ThankYouView.as_view(),name='thank_you'),
    path('create_teacher',TeacherCreateView.as_view(),name='create_teacher'),
    path('list_teacher/',TeacherListView.as_view(),name='list_teacher'),
    path('delete_teacher/<int:pk>/',TeacherDeleteView.as_view(),name="delete_teacher"),
    path('update_teacher/<int:pk>/',TeacherUpdateView.as_view(),name='update_teacher'),
    path("teacher/<int:pk>/",TeacherDetailView.as_view(),name='detail_teacher')
]

11-Django-Class-Based-Views/school_site/school_site/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('classroom/',include('classroom.urls'))
]

11-Django-Class-Based-Views/school_site/classroom/models.py
from django.db import models

# Create your models here.
class Teacher(models.Model):
    first_name = models.CharField(max_length=30)
    last_name = models.CharField(max_length=30)
    subject = models.CharField(max_length=30)

    def __str__(self):
        return f"{self.first_name} {self.last_name} teaches {self.subject}"

11-Django-Class-Based-Views/school_site/classroom/forms.py
from django import forms 

class ContactForm(forms.Form):
    name = forms.CharField()
    message = forms.CharField(widget=forms.Textarea)

11-Django-Class-Based-Views/school_site/classroom/views.py
from django.shortcuts import render
from django.urls import reverse,reverse_lazy
from django.views.generic import TemplateView, CreateView,DetailView, FormView,ListView,UpdateView,DeleteView
from classroom.models import Teacher
from classroom.forms import ContactForm
# Create your views here.

class HomeView(TemplateView):
    template_name = 'classroom/home.html'

class ThankYouView(TemplateView):
    template_name = 'classroom/thank_you.html'

class ContactFormView(FormView):
    # Specify form to use (do not create an instance of the form!)
    form_class = ContactForm
    # Point to template to pass form
    template_name = 'classroom/contact.html'
    # Where to go upon valid form completion
    # DO NOT FORGET THE FIRST /
    # NOTE THIS IS A URL, NOT A TEMPLATE .HTML!!
    # success_url = '/classroom/thank_you/'
    # https://stackoverflow.com/questions/48669514/difference-between-reverse-and-reverse-lazy-in-django
    success_url = reverse_lazy('classroom:thank_you')

    def form_valid(self, form):
        # This method is called when valid form data has been POSTed.
        # It should return an HttpResponse.
         
        # Do stuff with form here! 
        # form.save() if ModelForm
        print(form.cleaned_data)
        return super().form_valid(form)

    

class TeacherCreateView(CreateView):
    # AUTO CONNECTS TO A TEMPLATE WITH THE NAME:
    # model_form.html
    # Make sure to match this template name schema!!
    model = Teacher
    # fields = ['name']
    fields = '__all__'

    success_url = reverse_lazy('classroom:thank_you')

class TeacherListView(ListView):
    model = Teacher 
    # Peform any .filter() you want here to only list certain items
    queryset = Teacher.objects.order_by('first_name')
    # customize the name of the object_list sent to template
    context_object_name = 'object_list'

class TeacherUpdateView(UpdateView):
    # Note! Uses model_form.html file as well
    # same form as CreateView
    model = Teacher
    fields = "__all__"
    success_url = reverse_lazy('classroom:list_teacher') 

class TeacherDeleteView(DeleteView):
    # Requires model_confirm_delete.html template name
    model = Teacher
    success_url = reverse_lazy('classroom:list_teacher')

class TeacherDetailView(DetailView):
    model = Teacher 
    # uses template with model_detail.html schema

11-Django-Class-Based-Views/school_site/classroom/templates/classroom/contact.html
<h1>Form View Template</h1>
<form method="POST">
    {% csrf_token %}
    {{form.as_p}}
    <input type="submit">
</form>

11-Django-Class-Based-Views/school_site/classroom/templates/classroom/home.html
 <h1>Classroom Home Page</h1>
 <a href="{% url 'classroom:contact' %}">Contact Page Link</a>
 <br>
 <a href="{% url 'classroom:create_teacher' %}">Create new Teacher Link</a>
 <br>
 <a href="{% url 'classroom:list_teacher' %}">List Teacher Link</a>
 

11-Django-Class-Based-Views/school_site/classroom/templates/classroom/teacher_confirm_delete.html
<h1>Are you sure you want to delete this teacher?</h1>
<h2>Teacher to delete {{teacher}}</h2>

<form action="" method="post">
    {% csrf_token %}
    <input type="submit" value="Confirm DELETE">
</form>

11-Django-Class-Based-Views/school_site/classroom/templates/classroom/teacher_detail.html
<h2>Detail view for Teacher:</h2>
{{teacher}}

11-Django-Class-Based-Views/school_site/classroom/templates/classroom/teacher_form.html
<h1>TEACHER FORM</h1>
<form method="POST">
    {% csrf_token %}
    {{form.as_p}}
    <input type="submit" value="Submit">
</form>

11-Django-Class-Based-Views/school_site/classroom/templates/classroom/teacher_list.html
<h1>List of Teachers</h1>
<ul>
    {% for teacher in object_list  %}
        <li>{{teacher.first_name}} {{teacher.last_name}}</li>
    {% endfor %}
</ul>
<br>
{% comment %} 
ADD DETAIL LINK FOR EACH ITEM IN LIST 
{% endcomment %}
<ul>
    {% for teacher in object_list  %}
        <li><a href="/classroom/teacher/{{teacher.id}}">{{teacher.first_name}}</a></li>
    {% endfor %}
</ul>
<br>
{% comment %} 
ADD UPDATE AND DELETE LINKS
{% endcomment %}
<ul>
    {% for teacher in object_list  %}
        <li><a href="/classroom/teacher/{{teacher.id}}">DETAIL: {{teacher.first_name}}</a></li>
        <li><a href="/classroom/update_teacher/{{teacher.id}}">UPDATE: {{teacher.first_name}}</a></li>
        <li><a href="/classroom/delete_teacher/{{teacher.id}}">DELETE: {{teacher.first_name}}</a></li>
        <br>
        <br>
    {% endfor %}
</ul>
<br>

11-Django-Class-Based-Views/school_site/classroom/templates/classroom/thank_you.html
<h1>Thank you!</h1>
<h2><a href="{% url 'classroom:home' %}">Go back home</a></h2>